fastlane_require "dotenv"

before_all do
  Dotenv.load ".env.secret"
end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Sync signing"
  lane :signing do
    match#(readonly: true)

  end

  desc "Build Binary"
  lane :build do
    signing
    build_ios_app(scheme: "App_Main")
  end

  desc "Release to TestFlight"
  lane :release_testflight do
    build

    upload_to_testflight
  end

end

platform :mac do


  desc "Sync signing"
  lane :signing do
  end

  desc "Build Binary"
  lane :build do
    signing
  end

  desc "Release to TestFlight"
  lane :release_beta do
    build
  end

end
